export const PALETTE = [
  { hex: '#F9FFFE', name: 'White' },
  { hex: '#9D9D97', name: 'Light Gray' },
  { hex: '#474F52', name: 'Gray' },
  { hex: '#1D1D21', name: 'Black' },
  { hex: '#835432', name: 'Brown' },
  { hex: '#8B6914', name: 'Dirt' },
  { hex: '#6B4423', name: 'Wood' },
  { hex: '#5c3818', name: 'Dark Wood' },
  { hex: '#5a8f29', name: 'Grass' },
  { hex: '#80C71F', name: 'Lime' },
  { hex: '#2d7a2d', name: 'Leaves' },
  { hex: '#169C9C', name: 'Cyan' },
  { hex: '#2471A3', name: 'Water' },
  { hex: '#87CEEB', name: 'Sky' },
  { hex: '#4AEDD9', name: 'Diamond' },
  { hex: '#3AB3DA', name: 'Light Blue' },
  { hex: '#B02E26', name: 'Red' },
  { hex: '#F9801D', name: 'Orange' },
  { hex: '#FF6A00', name: 'Lava' },
  { hex: '#FED83D', name: 'Yellow' },
  { hex: '#FFD700', name: 'Gold' },
  { hex: '#F38BAA', name: 'Pink' },
  { hex: '#8932B8', name: 'Purple' },
  { hex: '#C74EBD', name: 'Magenta' },
]
